apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
    spec:
      containers:
        - name: web
          image: deividdua32/conversao-temperatura:v1
          ports:
            - containerPort: 80
