apiVersion: v1
kind: Pod
metadata:
  name:  meupod
spec:
  containers:
    - name: web
      image: deividdua32/conversao-temperatura:v1
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name:  meupod-label
  labels:
    app: web
spec:
  containers:
    - name: web
      image: deividdua32/conversao-temperatura:v1
      ports:
        - containerPort: 80